// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await tializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWV-sOLhkD87DcODEzH2FBCsyL43vT8U',
    appId: '1:465144981289:web:927fb9d2662ba1e20e3938',
    messagingSenderId: '465144981289',
    projectId: 'mynotes-220622',
    authDomain: 'mynotes-220622.firebaseapp.com',
    storageBucket: 'mynotes-220622.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_vVHJNu5P20HbYSuRtWIfqjKsJCkoBw',
    appId: '1:465144981289:android:566e8caabba854d40e3938',
    messagingSenderId: '465144981289',
    projectId: 'mynotes-220622',
    storageBucket: 'mynotes-220622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAmLYp_PYfWqh972kegmNM7vC-JsycmyM',
    appId: '1:465144981289:ios:115a1436286186b10e3938',
    messagingSenderId: '465144981289',
    projectId: 'mynotes-220622',
    storageBucket: 'mynotes-220622.appspot.com',
    iosClientId:
        '465144981289-5sdg2cpn6pr5ood62dkqrsp0k8nd47t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAmLYp_PYfWqh972kegmNM7vC-JsycmyM',
    appId: '1:465144981289:ios:115a1436286186b10e3938',
    messagingSenderId: '465144981289',
    projectId: 'mynotes-220622',
    storageBucket: 'mynotes-220622.appspot.com',
    iosClientId:
        '465144981289-5sdg2cpn6pr5ood62dkqrsp0k8nd47t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );
}
